eval:
  benchmark: mmvet

inference:
  backbone: bagel
  backbone_cfg:
    bagel_root: ${UMM_CODEBASE}/src/umm/backbones/bagel/Bagel
    model_path: ${UMM_MODEL_CACHE}/bagel/BAGEL-7B-MoT
    max_mem_per_gpu: 80GiB
    offload_folder: ./tmp/offload
    seed: 42

    understanding_cfg:
      max_think_token_n: 1000
      do_sample: false

mmvet:
  datasets: [mmvet]
  out_dir: output/mmvet/bagel
  score_output_path: output/mmvet/bagel/summary.json
  dataset_paths:
    image_root: data/mm-vet/mm-vet/images
    question: data/mm-vet/llava-mm-vet.jsonl
