eval:
  benchmark: mmvet

inference:
  backbone: omnigen2
  backbone_cfg:
    model_path: /model_cache/omnigen2/OmniGen2
    omnigen2_root: /workspace/model/OmniGen2
    device: cuda:0
    device_map: cuda:0
    torch_dtype: bfloat16
    enable_cpu_offload: false
    enable_sequential_cpu_offload: false
    generation_cfg:
      num_inference_steps: 50
      seed: 42

    understanding_cfg:
      max_new_tokens: 2048

mmvet:
  datasets: [mmvet]
  out_dir: /output-apr4/mmvet/omnigen2
  score_output_path: /output-apr4/mmvet/omnigen2/summary.json
  dataset_paths:
    image_root: /workspace/data/mm-vet/mm-vet/images
    question: /workspace/data/mm-vet/llava-mm-vet.jsonl
