eval:
  benchmark: mme

inference:
  backbone: bagel
  backbone_cfg:
    bagel_root: ${UMM_CODEBASE}/src/umm/backbones/bagel/Bagel
    model_path: ${UMM_MODEL_CACHE}/bagel/BAGEL-7B-MoT
    max_mem_per_gpu: 80GiB
    offload_folder: ./tmp/offload
    seed: 42

    understanding_cfg:
      max_think_token_n: 1000
      do_sample: false

mme:
  root: src/umm/eval/internvl_chat/eval/mme/Your_Results
  image_root: data/mme/MME_Benchmark_release_version
  out_dir: output/mme/bagel
  score_output_path: output/mme/bagel/summary.json
  run_calculation: true

