eval:
  benchmark: mme

inference:
  backbone: show_o
  backbone_cfg:
    version: 1
    model_path: ${UMM_MODEL_CACHE}/show_o/show-o-w-clip-vit-512x512
    show_o_root: ${UMM_CODEBASE}/model/Show-o
    vq_model_path: ${UMM_MODEL_CACHE}/show_o/magvitv2
    seed: 42
    torch_dtype: bfloat16
    understanding_cfg:
      max_new_tokens: 2048
      do_sample: false
      use_clip_vit: true

mme:
  root: src/umm/eval/internvl_chat/eval/mme/Your_Results
  image_root: data/mme/MME_Benchmark_release_version
  out_dir: output/mme/show_o
  score_output_path: output/mme/show_o/summary.json
  run_calculation: true
