eval:
  benchmark: mme

inference:
  backbone: omnigen2
  backbone_cfg:
    model_path: /post_train_model_cache/post_train/omnigen2/
    omnigen2_root: /workspace/model/OmniGen2
    device: cuda:0
    device_map: cuda:0
    torch_dtype: bfloat16
    enable_cpu_offload: false
    enable_sequential_cpu_offload: false

    understanding_cfg:
      max_new_tokens: 2048

mme:
  root: /workspace/src/umm/eval/internvl_chat/eval/mme/Your_Results
  image_root: /workspace/data/mme/MME_Benchmark_release_version
  out_dir: /output-apr4/mme/omnigen2_sft_debug
  run_calculation: false
  max_samples: 2
