inference:
  backbone: ovis_u1
  backbone_cfg:
    model_path: ${UMM_MODEL_CACHE}/ovis_u1/Ovis-U1-3B
    generation_cfg:
      height: 1024
      width: 1024
      num_steps: 50
      txt_cfg: 5.0

dpg_bench:
  prompts_dir: eval/generation/dpg_bench/prompts
  image_output_dir: output/dpg_bench/ovis_u1
  resolution: 512
  score_output_path: output/dpg_bench/ovis_u1/final_score.json
  images_per_prompt: 4
  gpus: 1
  overwrite: false
  skip_eval: false
