inference:
  backbone: emu3_5
  backbone_cfg:
    model_path: /model_cache/emu3_5/Emu3.5-Image
    vq_path: /model_cache/emu3_5/Emu3.5-VisionTokenizer
    emu3_5_root: /workspace/model/Emu3.5
    use_vllm: true
    tensor_parallel_size: 2
    gpu_memory_utilization: 0.7
    classifier_free_guidance: 5.0
    image_area: 1048576

    generation_cfg:
      max_new_tokens: 5120
      classifier_free_guidance: 5.0

dpg_bench:
  prompts_dir: /workspace/eval/generation/dpg_bench/prompts
  image_output_dir: /outputs/dpg_bench/emu3_5
  resolution: 512
  eval_python: python
  score_output_path: /outputs/dpg_bench/emu3_5/final_score.json
  images_per_prompt: 4
  gpus: 1
  overwrite: false
  skip_eval: false
