inference:
  backbone: bagel
  backbone_cfg:
    model_path: /post_train_model_cache/post_train/IRG/
    bagel_root: /workspace/model/Bagel
    max_mem_per_gpu: 80GiB
    offload_folder: ./tmp/offload
    seed: 42
    distributed_single_gpu: true
    generation_cfg:
      num_timesteps: 50

dpg_bench:
  prompts_dir: /workspace/eval/generation/dpg_bench/prompts
  image_output_dir: /outputs/dpg_bench/bagel_IRG
  resolution: 512
  eval_python: python
  score_output_path: /outputs/dpg_bench/bagel_IRG/final_score.json
  images_per_prompt: 4
  gpus: 1
  bagel_multiprocess: true
  overwrite: false
  skip_eval: false
