eval:
  benchmark: wise

wise:
  data_root: eval/generation/wise/data
  out_dir: output/wise/blip3o_sft
  max_samples: 0
  resume: true
  score_output_path: output/wise/blip3o_sft/summary.json
  mode: generate  # full | generate | score
  vlm_eval:
    enabled: true
    model_name: ${UMM_MODEL_CACHE}/evaluator/Qwen2.5-VL-72B-Instruct
    max_new_tokens: 512
    max_retries: 2
  run_calculate: true

inference:
  backbone: blip3o
  backbone_cfg:
    model_path: ${UMM_POST_TRAIN_MODEL_CACHE}/post_train/blip3o
    blip3o_root: ${UMM_CODEBASE}/model/BLIP3o
    device: "cuda:0"
    torch_dtype: bfloat16
    scale: 0
    seq_len: 729
    top_p: 0.95
    top_k: 1200
