eval:
  benchmark: mmbench

inference:
  backbone: show_o
  backbone_cfg:
    version: 1
    model_path: ${UMM_MODEL_CACHE}/show_o/show-o-w-clip-vit-512x512
    show_o_root: ${UMM_CODEBASE}/model/Show-o
    vq_model_path: ${UMM_MODEL_CACHE}/show_o/magvitv2
    seed: 42
    torch_dtype: bfloat16
    understanding_cfg:
      max_new_tokens: 2048
      do_sample: false
      use_clip_vit: true

mmbench:
  datasets: [mmbench_dev_20230712]
  out_dir: output/mmbench/show_o
  score_output_path: output/mmbench/show_o/summary.json
