eval:
  benchmark: mmbench

inference:
  backbone: omnigen2
  backbone_cfg:
    model_path: /post_train_model_cache/post_train/omnigen2/
    omnigen2_root: /workspace/model/OmniGen2
    device: cuda:0
    device_map: cuda:0
    torch_dtype: bfloat16
    enable_cpu_offload: false
    enable_sequential_cpu_offload: false

    understanding_cfg:
      max_new_tokens: 2048

mmbench:
  datasets: [mmbench_dev_20230712]
  out_dir: /output-apr4/mmbench/omnigen2_sft
  score_output_path: /output-apr4/mmbench/omnigen2_sft/summary.json
  resume: true
