eval:
  benchmark: imgedit

imgedit:
  origin_img_root: ${UMM_DATASETS}/imgedit/Benchmark
  out_dir: output/imgedit/bagel_unicot
  mode: generate
  resume: true
  model_name: bagel
  edit_type: all
  suite: all
  run_calculate: true
  score_output_path: output/imgedit/bagel_unicot/summary.json
  vlm_eval:
    backbone: qwen25vl
    model_path: ${UMM_MODEL_CACHE}/evaluator/Qwen2.5-VL-72B-Instruct

inference:
  backbone: bagel
  backbone_cfg:
    model_path: ${UMM_POST_TRAIN_MODEL_CACHE}/post_train/unicot/merge/
    bagel_root: ${UMM_CODEBASE}/model/Bagel
    max_mem_per_gpu: "80GiB"
    offload_folder: ./tmp/offload
    seed: 42
    editing_cfg:
      cfg_text_scale: 4.0
      cfg_img_scale: 2.0
      num_timesteps: 50
  request:
    params: {}
