eval:
  benchmark: uni_mmmu

inference:
  backbone: bagel
  backbone_cfg:
    model_path: /post_train_model_cache/post_train/IRG/
    bagel_root: /workspace/model/Bagel
    offload_folder: ./tmp/offload_bagel0
    max_mem_per_gpu: "80GiB"
    seed: 42
    generation_cfg:
      cfg_text_scale: 4.0
      cfg_img_scale: 1.0
      num_timesteps: 25
    editing_cfg:
      cfg_text_scale: 4.0
      cfg_img_scale: 2.0
      num_timesteps: 25
    understanding_cfg:
      max_think_token_n: 500
      do_sample: false

uni_mmmu:
  data_root: /datasets/uni_mmmu/Uni-MMMU-Eval/data
  tasks: all
  out_dir: /outputs/uni_mmmu/bagel_IRG-step25think500
  max_samples: 0
  resume: true
  score_output_path: /outputs/uni_mmmu/bagel_IRG-step25think500/overall_summary.json
