eval:
  benchmark: mathvista

inference:
  backbone: emu3
  backbone_cfg:
    emu_root: ${UMM_CODEBASE}/model/Emu3
    model_path: BAAI/Emu3-Chat
    vq_hub: BAAI/Emu3-VisionTokenizer
    device_map: cuda:0
    device: cuda:0
    torch_dtype: bfloat16
    attn_implementation: flash_attention_2

    generation_cfg:
      max_new_tokens: 1024

mathvista:
  mode: generate
  resume: true
  gt_file: data/MathVista/annot_testmini.json
  root: AI4Math/MathVista
  cache_dir: data/MathVista
  datasets: [MathVista_testmini]
  out_dir: output/mathvista/emu3
  score_output_path: output/mathvista/emu3/summary.json
  llm_extract:
    model_path: ${UMM_MODEL_CACHE}/evaluator/Qwen3-32B-AWQ
    max_new_tokens: 2048
