eval:
  benchmark: mmmu

inference:
  backbone: ovis_u1
  backbone_cfg:
    model_path: ${UMM_MODEL_CACHE}/ovis_u1/Ovis-U1-3B

    understanding_cfg:
      max_new_tokens: 2048
      do_sample: false

mmmu:
  root: MMMU/MMMU
  cache_dir: data/MMMU
  datasets: [MMMU_validation]
  out_dir: output/mmmu/ovis_u1
  score_output_path: output/mmmu/ovis_u1/summary.json
  run_calculation: true
  max_images: 1
